apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  storageClassName: "ebs-expense" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      # has to match .spec.template.metadata.labels
      component: mysql
      project: expense
      tier: db 
  serviceName: "mysql-headless" # provide headless service name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
       # has to match .spec.selector.matchLabels
        component: mysql
        project: expense
        tier: db 
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # PVC declaration, it is mandatory
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-expense"
      resources:
        requests:
          storage: 1G