kind: Service
apiVersion: v1
metadata:
 name: mysql-headless
 namespace: expense
spec:
 clusterIP: None # this is called headless
 selector:
  component: mysql
  project: expense
  tier: db
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 
---
kind: Service
apiVersion: v1
metadata:
 name: mysql
 namespace: expense
spec:
 selector:
  component: mysql
  project: expense
  tier: db
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  storageClassName: "ebs-expense" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
    # has to match .spec.template.metadata.labels
      component: mysql
      project: expense
      tier: db 
  serviceName: "mysql-headless" #headless metadata name
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        # has to match .spec.template.metadata.labels
        component: mysql
        project: expense
        tier: db 
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql 
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-expense"
      resources:
        requests:
          storage: 1G




